---
# This playbook sets up a Pi as a PM monitor

- name: configure pi
  hosts: "{{ inventory_hostname }}"
  become_user: root
  become: yes
  tasks:
    - name: print facts
      debug:
        var: ansible_facts

  roles:
    - pi-common
