---
- name: Update current packages
  apt:
    force_apt_get: yes
    update_cache: yes
    upgrade: yes

- name: Install new packages
  apt:
    name: [
           'python3',
           'python3-pip',
           'vim',
           'python-smbus',
           'i2c-tools',
           'supervisor',
           'libopenjp2-7',
           'libtiff5',
           'fonts-dejavu'
          ]
    state: latest
    force_apt_get: yes

- name: make python3 the system default
  command:
    cmd: update-alternatives --install /usr/bin/python python /usr/bin/python3 10

- name: install pip packages
  pip:
    executable: /usr/bin/pip3
    name:
      - pyserial
      - adafruit-io
      - gpiozero
      - datadog
      - adafruit-circuitpython-ssd1306
      - pillow
      - RPI.GPIO
      - adafruit-blinka

- name: enable SPI
  lineinfile:
    path: /boot/config.txt
    line: dtparam=spi=on

- name: enable I2C
  lineinfile:
    path: /boot/config.txt
    line: dtparam=i2c_arm=on

- name: enable I2C kernel module
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: i2c-dev

- name: use vim
  lineinfile:
    dest: "{{ item }}/.bashrc"
    line: 'export EDITOR=vim'
  with_items:
    - /home/pi
    - /root

- name: US keyboard layout
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644

- name: change the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: set the hostname fact also
  set_fact: ansible_hostname={{ hostname }}
  when: hostname is defined

- name: add local host name to /etc/hosts
  replace:
    path: /etc/hosts
    regexp: '\slocalhost'
    replace: "  localhost {{ hostname }}"
  when: hostname is defined

- name: set the timezone to Sydney
  file:
    src: /usr/share/zoneinfo/Australia/Sydney
    dest: /etc/localtime
    owner: root
    group: root
    mode: 0644
    state: link

- name: get the sds011 library
  unarchive:
    src: https://github.com/ikalchev/py-sds011/archive/master.zip
    dest: /home/pi
    owner: pi
    group: pi
    mode: 0755
    remote_src: yes
    creates: /home/pi/sds011

- name: move sds011 library dir
  command:
    cmd: mv /home/pi/py-sds011-master/sds011 /home/pi/
    creates: /home/pi/sds011

- name: cleanup DL dir
  file:
    path: /home/pi/py-sds011-master
    state: absent

- name: install code
  copy:
    src: pm.py
    dest: /home/pi/pm.py
    owner: pi
    group: pi
    mode: 0644

- name: Setup the PM monitor cron
  cron:
    name: "take a PM reading"
    minute: "*/5"
    user: "pi"
    job: "python /home/pi/pm.py"

- name: ssh service state
  service:
    name: ssh
    state: started
    enabled: yes
