---
- name: update current packages
  apt:
    force_apt_get: yes
    update_cache: yes
    upgrade: yes

- name: Install new packages
  apt:
    name: "{{ item }}"
    state: present
    force_apt_get: yes
  with_items:
    - python3
    - python3-pip
    - vim
    - sysstat
    - python-smbus
    - i2c-tools
    - supervisor
    - libopenjp2-7
    - libtiff5

- name: install pip packages
  pip:
    executable: /usr/bin/pip3
    name:
      - pyserial
      - adafruit-io
      - gpiozero
      - datadog
      - adafruit-circuitpython-ssd1306
      - pillow
      - RPI.GPIO
      - adafruit-blinka

- name: enable SPI
  lineinfile:
    path: /boot/config.txt
    line: dtparam=spi=on

- name: enable IC2
  lineinfile:
    path: /boot/config.txt
    line: dtparam=ic2_arm=on

- name: enable IC2 kernel module
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: ic2-dev

- name: add dd keys to environment
  blockinfile:
    path: /etc/environment
    block: |
      DD_APP_KEY={{DD_APP_KEY}}
      DD_API_KEY={{DD_API_KEY}}

- name: Download Datadog agent source
  get_url:
    url: https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh
    dest: /tmp/setup_agent.sh
    mode: "0755"

- name: Run datadog agent install
  shell: DD_API_KEY={{DD_API_KEY}} DD_SKIP_INTEGRATIONS=1 sh -c /tmp/setup_agent.sh
  args:
    chdir: /tmp
    creates: /root/.datadog-agent/bin/agent

- name: use vim
  lineinfile:
    dest: "{{ item }}/.bashrc"
    line: 'export EDITOR=vim'
  with_items:
    - /home/pi
    - /root

- name: US keyboard layout
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644

- name: change the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: set the hostname fact also
  set_fact: ansible_hostname={{ hostname }}
  when: hostname is defined

- name: add local host name to /etc/hosts
  replace:
    path: /etc/hosts
    regexp: '\slocalhost'
    replace: "  localhost {{ hostname }}"
  when: hostname is defined

- name: set the timezone to Sydney
  file:
    src: /usr/share/zoneinfo/Australia/Sydney
    dest: /etc/localtime
    owner: root
    group: root
    mode: 0644
    state: link

- cron: name="send data"
    minute="*/5"
    user="pi"
    job=":"

- name: install code
  copy:
    src: pm.py
    dest: /home/pi/pm.py
    owner: pi
    group: pi
    mode: 0644

- name: get the sds011 library
  unarchive:
    src: https://github.com/ikalchev/py-sds011/archive/master.zip
    dest: /home/pi
    owner: pi
    group: pi
    mode: 0755
    remote_src: yes
    creates: /home/pi/sds011

- name: move sds011 library dir
  command:
    cmd: mv /home/pi/py-sds011-master/sds011 /home/pi/
    creates: /home/pi/sds011

- name: cleanup DL dir
  file:
    src: /home/pi/py-sds011-master
    state: absent

- name: ssh service state
  service: name=ssh state=started enabled=yes
