---
- name: Update current packages
  apt:
    force_apt_get: yes
    update_cache: yes
    upgrade: yes

- name: Install new packages
  apt:
    name: [
           'python3',
           'python3-pip',
           'vim',
          ]
    state: latest
    force_apt_get: yes

- name: make python3 the system default
  command:
    cmd: update-alternatives --install /usr/bin/python python /usr/bin/python3 10

- name: install pip packages
  pip:
    executable: /usr/bin/pip3
    name:
      - datadog
      - adafruit-circuitpython-shtc3

- name: enable SPI
  lineinfile:
    path: /boot/config.txt
    line: dtparam=spi=on

- name: enable I2C
  lineinfile:
    path: /boot/config.txt
    line: dtparam=i2c_arm=on

- name: enable I2C kernel module
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: i2c-dev

- name: use vim
  lineinfile:
    dest: "{{ item }}/.bashrc"
    line: 'export EDITOR=vim'
  with_items:
    - /home/pi
    - /root

- name: disable visual mode in vim
  lineinfile:
    dest: /etc/vim/vimrc
    line: "set mouse-=a"

- name: US keyboard layout
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644

- name: change the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: set the hostname fact also
  set_fact: ansible_hostname={{ hostname }}
  when: hostname is defined

- name: add local host name to /etc/hosts
  replace:
    path: /etc/hosts
    regexp: '\slocalhost'
    replace: "  localhost {{ hostname }}"
  when: hostname is defined

- name: set the timezone to Sydney
  file:
    src: /usr/share/zoneinfo/Australia/Sydney
    dest: /etc/localtime
    owner: root
    group: root
    mode: 0644
    state: link


- name: install code
  copy:
    src: temp-humidity.py
    dest: /home/pi/temp_humidity.py
    owner: pi
    group: pi
    mode: 0644

- name: Setup the PM monitor cron
  cron:
    name: "take a temp reading"
    minute: "1-59/5"
    user: "pi"
    job: "python /home/pi/temp_humidity.py"

- name: ssh service state
  service:
    name: ssh
    state: started
    enabled: yes
